### ISSUE TITLE
Unexpected value 'ColorPickerModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by dguisinger** [AndyMeps/ng2-color-picker#3]
I'm getting the following error:

Error: Unexpected value 'ColorPickerModule' imported by the module 'AppModule'

My initialization code is:
@NgModule({
    bootstrap: [AppComponent],
    imports:
    [
        UniversalModule, // Must be first import. 
        // This automatically imports BrowserModule, HttpModule, and JsonpModule too.
        // FormsModule, 
        RouterModule.forRoot(routes),
        Ng2BootstrapModule,
        NgReduxModule.forRoot(),
        ColorPickerModule
    ],
...

Can you see anything wrong with this?

Also, I see your module imports Angular 2.4.4; the rest of my project is stuck on 2.2.0 for Angular Universal support.   This error is happening during a server side pre-render.  I'm not sure if its happening in the client side.  Any ideas?

**Comment by AndyMeps** [comment]
Silly question but best to check, are you importing it?

```typescript
import { ColorPickerModule } from 'ng2-color-picker';
```

**Comment by dguisinger** [comment]
I am indeed.  Doesn't make a lot of sense, it's not generating an error in my editor (visual studio), it sees it as valid code... but apparently there is something it doesn't like when the module is listed in my import section when the app launches.

**Comment by AndyMeps** [comment]
Hi dguisinger,

Sorry for not getting back to you, did you make any progress? If not I'm happy to look in to this if you can provide further details.

Cheers,

Andy

**Comment by dguisinger** [comment]
I never did figure out the issue.  I ended up moving from Ng2-Bootstrap to
Ng-Bootstrap which is based on Bootstrap 4, so I'm no longer on a codebase
compatible with ng2-color-picker.

**Comment by AndyMeps** [comment]
Closing, no reproduction.
